name: sudoku_web
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  ###
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.3
  shared_preferences: ^2.5.4
  intl: ^0.20.2
  fade_out_particle: ^1.2.2
  ###
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: ComicRelief
      fonts:
        - asset: assets/fonts/ComicRelief-Bold.ttf

# dart run change_app_package_name:main com.example.test1
# dart run flutter_native_splash:create
# flutter build apk --split-per-abi